/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as SignupImport } from './routes/signup'
import { Route as SignInImport } from './routes/signIn'
import { Route as ResetPasswordImport } from './routes/resetPassword'
import { Route as OtpImport } from './routes/otp'
import { Route as HomePageImport } from './routes/homePage'
import { Route as ForgotPasswordImport } from './routes/forgotPassword'
import { Route as IndexImport } from './routes/index'
import { Route as UserIdImport } from './routes/user/$id'

// Create/Update Routes

const SignupRoute = SignupImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRoute,
} as any)

const SignInRoute = SignInImport.update({
  id: '/signIn',
  path: '/signIn',
  getParentRoute: () => rootRoute,
} as any)

const ResetPasswordRoute = ResetPasswordImport.update({
  id: '/resetPassword',
  path: '/resetPassword',
  getParentRoute: () => rootRoute,
} as any)

const OtpRoute = OtpImport.update({
  id: '/otp',
  path: '/otp',
  getParentRoute: () => rootRoute,
} as any)

const HomePageRoute = HomePageImport.update({
  id: '/homePage',
  path: '/homePage',
  getParentRoute: () => rootRoute,
} as any)

const ForgotPasswordRoute = ForgotPasswordImport.update({
  id: '/forgotPassword',
  path: '/forgotPassword',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const UserIdRoute = UserIdImport.update({
  id: '/user/$id',
  path: '/user/$id',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/forgotPassword': {
      id: '/forgotPassword'
      path: '/forgotPassword'
      fullPath: '/forgotPassword'
      preLoaderRoute: typeof ForgotPasswordImport
      parentRoute: typeof rootRoute
    }
    '/homePage': {
      id: '/homePage'
      path: '/homePage'
      fullPath: '/homePage'
      preLoaderRoute: typeof HomePageImport
      parentRoute: typeof rootRoute
    }
    '/otp': {
      id: '/otp'
      path: '/otp'
      fullPath: '/otp'
      preLoaderRoute: typeof OtpImport
      parentRoute: typeof rootRoute
    }
    '/resetPassword': {
      id: '/resetPassword'
      path: '/resetPassword'
      fullPath: '/resetPassword'
      preLoaderRoute: typeof ResetPasswordImport
      parentRoute: typeof rootRoute
    }
    '/signIn': {
      id: '/signIn'
      path: '/signIn'
      fullPath: '/signIn'
      preLoaderRoute: typeof SignInImport
      parentRoute: typeof rootRoute
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupImport
      parentRoute: typeof rootRoute
    }
    '/user/$id': {
      id: '/user/$id'
      path: '/user/$id'
      fullPath: '/user/$id'
      preLoaderRoute: typeof UserIdImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/forgotPassword': typeof ForgotPasswordRoute
  '/homePage': typeof HomePageRoute
  '/otp': typeof OtpRoute
  '/resetPassword': typeof ResetPasswordRoute
  '/signIn': typeof SignInRoute
  '/signup': typeof SignupRoute
  '/user/$id': typeof UserIdRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/forgotPassword': typeof ForgotPasswordRoute
  '/homePage': typeof HomePageRoute
  '/otp': typeof OtpRoute
  '/resetPassword': typeof ResetPasswordRoute
  '/signIn': typeof SignInRoute
  '/signup': typeof SignupRoute
  '/user/$id': typeof UserIdRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/forgotPassword': typeof ForgotPasswordRoute
  '/homePage': typeof HomePageRoute
  '/otp': typeof OtpRoute
  '/resetPassword': typeof ResetPasswordRoute
  '/signIn': typeof SignInRoute
  '/signup': typeof SignupRoute
  '/user/$id': typeof UserIdRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/forgotPassword'
    | '/homePage'
    | '/otp'
    | '/resetPassword'
    | '/signIn'
    | '/signup'
    | '/user/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/forgotPassword'
    | '/homePage'
    | '/otp'
    | '/resetPassword'
    | '/signIn'
    | '/signup'
    | '/user/$id'
  id:
    | '__root__'
    | '/'
    | '/forgotPassword'
    | '/homePage'
    | '/otp'
    | '/resetPassword'
    | '/signIn'
    | '/signup'
    | '/user/$id'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  HomePageRoute: typeof HomePageRoute
  OtpRoute: typeof OtpRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SignInRoute: typeof SignInRoute
  SignupRoute: typeof SignupRoute
  UserIdRoute: typeof UserIdRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  HomePageRoute: HomePageRoute,
  OtpRoute: OtpRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SignInRoute: SignInRoute,
  SignupRoute: SignupRoute,
  UserIdRoute: UserIdRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/forgotPassword",
        "/homePage",
        "/otp",
        "/resetPassword",
        "/signIn",
        "/signup",
        "/user/$id"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/forgotPassword": {
      "filePath": "forgotPassword.tsx"
    },
    "/homePage": {
      "filePath": "homePage.tsx"
    },
    "/otp": {
      "filePath": "otp.tsx"
    },
    "/resetPassword": {
      "filePath": "resetPassword.tsx"
    },
    "/signIn": {
      "filePath": "signIn.tsx"
    },
    "/signup": {
      "filePath": "signup.tsx"
    },
    "/user/$id": {
      "filePath": "user/$id.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
